import cv2
img=cv2.imread("opencv-logo.png",1)
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(gray, 127, 255, 0)
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
cv2.drawContours(img,contours,-1,(0,255,0),3)
print("number of contours: "+str(len(contours)))
cv2.imshow("original",img)
cv2.imshow("gray",gray)
cv2.waitKey(0)
cv2.destroyAllWindows()
